################################################
LLList.class: \
LLList.java; javac LLList.java
################################################
LinkedTree.class: \
LinkedTree.java; javac LinkedTree.java
################################################
ChainedHashTable.class: \
ChainedHashTable.java; javac ChainedHashTable.java
################################################
clean:: ; rm -f *~
################################################
cleanall:: clean
cleanall:: ; rm -f *.class
################################################
