test: \
LinkedTree.class; java LinkedTree
LLList.class: \
LLList.java; javac LLList.java
LinkedTree.class: \
LinkedTree.java; javac LinkedTree.java

clean:: ; rm -f *~

cleanall:: clean
cleanall:: ; rm -f *.class

